version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017" #1st port is local one
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379" #1st port is local one

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432" #1st port is local one
    volumes:
      - postgres_data:/var/lib/postgresql/data/
   
  portainer:
    container_name: portainer #username:admin password:admin1234567
    restart: always
    ports:
      - "8080:8000" 
      - "9000:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - mongo_data:/data

  catalog.api:
    container_name: "catalog.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConectionString=mongodb://catalogdb:27017" #here catlogdb is container name
    depends_on: 
      - catalogdb # here catalog db is container name
    ports:
      - "8000:80" #8000 is local port no

  basket.api:
    container_name: "basket.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConectionString=basketdb:6379"
    depends_on: 
      - basketdb
    ports:
      - "8001:80"

