version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017" #1st port is local one
    volumes:
      - "mongo_data:/data/db"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379" #1st port is local one

  catalog.api:
    container_name: "catalog.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConectionString=mongodb://catalogdb:27017" #here catlogdb is container name
    depends_on: 
      - catalogdb # here catalog db is container name
    ports:
      - "8000:80" #8000 is local port no

  basket.api:
    container_name: "basket.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConectionString=basketdb:6379"
    depends_on: 
      - basketdb
    ports:
      - "8001:80"

