version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017" #1st port is local one
    volumes:
      - "mongo_data:/data/db"
  catalog.api:
    container_name: "catalog.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConectionString=mongodb://catalogdb:27017" #here catlogdb is container name
    depends_on: 
      - catalogdb # here catalog db is an image name
    ports:
      - "8000:80" #8000 is local port no
